apiVersion: v2
name: backend-chart
description: A Helm chart for shoeshop backend
type: application
version: 0.1.0
appVersion: "1.1.0"

dependencies:
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled 