replicaCount: 2

image:
  repository: toannd135/shoeshop-backend
  pullPolicy: IfNotPresent
  tag: "3dfe44a"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


service:
  port: 80
  targetPort: 8080
  type: LoadBalancer

secret:
  dbHost: "argocd-database-database-chart.shoeshop-data.svc.cluster.local"
  dbPort: "3306"
  dbName: "shoeshop"
  dbUsername: "dbshoeshop"
  dbPassword: "123456"
  idGoogle: "1026218825640-3cg8u2katgpf1026118gk2tsjl2b0n53.apps.googleusercontent.com"
  secretGoogle: "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"
  secretBase64: "qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ=="
  atTime: "900"
  rtTime: "2592000"

resources:
  requests:
    memory: "512Mi"
    cpu: "300m"
  limits:
    memory: "1024Mi"
    cpu: "1000m"


redis:
  enabled: false

externalRedis:
  host: "argocd-redis-master.shoeshop-data.svc.cluster.local"
  port: "6379"
  password: "123456"
  timeToLive: "3000"


healthCheck:
  enable: true
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 180
    periodSeconds: 20
    timeoutSeconds: 5
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
      scheme: HTTP
    initialDelaySeconds: 140
    periodSeconds: 10
    timeoutSeconds: 5

# ssl: ""
  # sslKey: "classpath:keystore.p12"
  # sslKeyPassword: "123456"
  # sslKeyType: "PKCS12"
  # sslKeyAlias: "tomcat"