replicaCount: 2

image:
  repository: toannd135/shoeshop-backend
  pullPolicy: IfNotPresent
  tag: "v1.1.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""  



service:
  port: 80 
  targetPort: 8080 
  type: LoadBalancer

secret:
  dbHost: db-shoeshop-database-chart
  dbPort: "3306"
  dbName: "shoeshop"
  dbUsername: "dbshoeshop"
  dbPassword: "123456"
  idGoogle: "1026218825640-3cg8u2katgpf1026118gk2tsjl2b0n53.apps.googleusercontent.com"
  secretGoogle: "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"
  secretBase64: "qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ=="
  atTime: "900"
  rtTime: "2592000"

resources:
  requests:
    memory: "384Mi" 
    cpu: "100m"         
  limits:
    memory: "768Mi" 
    cpu: "1000m"

healthCheck:
  enable: true
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTPS
    initialDelaySeconds: 200
    periodSeconds: 5
  readinessProbe:
    httpGet:
      path: /actuator/health
      port: 8080
      scheme: HTTPS
    initialDelaySeconds: 150
    periodSeconds: 10

redis:
  enabled: true
  image: 
    tag: "7.2"
  architecture: standalone
  auth:
    enabled: true
    password: "123456"
  
  master:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi 

    persistence:
      enabled: true
      size: 1Gi 
      storageClass: "standard"
