server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: shoes-shop

  datasource:
    url: jdbc:mysql://localhost:3306/shoeshop
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 100
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
            scope:
              - profile
              - email
  cache:
    type: redis
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
      timeout: 2000

  mail:
    host: smtp.gmail.com
    port: 587
    username: bookshop.dpdns.org@gmail.com
    password: fzyhqujnhakuiimh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

cloudinary:
  cloud-name: dljrbdc51
  api-key: 368851143165857
  api-secret: E5etQ4Jq1lu9s_okchG5FUZVa3s

app:
#  frontendUrl: https://shoeshopecommerce.dpdns.org
  frontendUrl: http://localhost:5173
  backendUrl: http://localhost:8080
  jwt:
    base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
    access-token-validity-in-seconds: 900
    refresh-token-validity-in-seconds: 2592000
  vnpay:
    base-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmn-code: GK3R1QML
    hash-secret: 4PTZHPLW8VRXA84N6DRHV6FPEW7A6LGD
    return-url: http://localhost:5173/checkoutSuccess
    cancel-url: http://localhost:8080/api/v1/payment/vnpay-cancel
    ipn-url: http://localhost:8080/api/v1/payment/vnpay-ipn
    version: 2.1.0
    command: pay
    order-type: 0
    order-info: test
    order-id: 1234567890