apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "backend-chart.fullname" . }}-configmap
  labels: {{ include "backend-chart.selectorLabels" . | nindent 4 }}
data:
  application.yaml: |
    server:
      port: 8080

    management:
      endpoints:
        web:
          exposure:
            include: health, info
      endpoint:
        health:
          show-details: always
      health:
        redis:
          enabled: false

    spring:
      application:
        name: shoes-shop

      datasource:
        url: jdbc:mysql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_NAME}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

      servlet:
        multipart:
          enabled: true
          max-file-size: 10MB
          max-request-size: 10MB

      jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQLDialect


      data:
        web:
          pageable:
            one-indexed-parameters: true
        redis:
          host: ${REDIS_HOST}
          port: ${REDIS_PORT}
          password: ${REDIS_PASSWORD}
          timeout: ${REDIS_TIMEOUT}

      security:
        oauth2:
          client:
            registration:
              google:
                client-id: ${CLIENT_ID_GOOGLE}
                client-secret: ${CLIENT_SECRET_GOOGLE}
                scope:
                  - profile
                  - email
      mail:
        host: smtp.gmail.com
        port: 587
        username: bookshop.dpdns.org@gmail.com
        password: fzyhqujnhakuiimh
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
                required: true
              ssl:
                trust: smtp.gmail.com
      jackson:
        deserialization:
          fail-on-unknown-properties: false

    cloudinary:
      cloud-name: dljrbdc51
      api-key: 368851143165857
      api-secret: E5etQ4Jq1lu9s_okchG5FUZVa3s

    app:
      cors:
        allowed-origins: http://localhost:3000,http://localhost:5173
      jwt:
        base64-secret: ${SECRET_BASE64}
        access-token-validity-in-seconds: ${AT_TIME}
        refresh-token-validity-in-seconds: ${RT_TIME}

