apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-chart.fullname" . }}-database-connection
type: Opaque
stringData:
  {{- with .Values.ssl }} 
    SSL_KEY_STORE: {{ index . "sslKey" | quote }}
    SSL_KEY_STORE_PASSWORD: {{ index . "sslKeyPassword" | quote}}
    SSL_KEY_STORE_TYPE: {{ index . "sslKeyType" | quote }}
    SSL_KEY_STORE_ALIAS:   {{ index . "sslKeyAlias" | quote}}
  {{- end }}
  {{- with .Values.secret }}
  SPRING_DATASOURCE_HOST: {{ index . "dbHost" | quote}}
  SPRING_DATASOURCE_PORT: {{ index . "dbPort" | quote }}
  SPRING_DATASOURCE_NAME: {{ index . "dbName" | quote }}
  SPRING_DATASOURCE_USERNAME: {{ index . "dbUsername" | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ index . "dbPassword" | quote }}
  CLIENT_ID_GOOGLE: {{ index . "idGoogle" | quote }}
  CLIENT_SECRET_GOOGLE: {{ index . "secretGoogle" | quote }}
  SECRET_BASE64: {{ index . "secretBase64" | quote }}
  AT_TIME: {{ index . "atTime" | quote }}
  RT_TIME: {{ index . "rtTime" | quote}}
  {{- end }}
  {{- with .Values.externalRedis }}
  REDIS_HOST: {{ index . "host" | quote }}
  REDIS_PORT: {{ index . "port" | quote }}
  REDIS_PASSWORD: {{ index . "password" | quote }}
  REDIS_TIMEOUT: {{ index . "timeToLive" | quote}}
  {{- end}}