apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend-chart.fullname" . }}-database-connection
type: Opaque
stringData:
  {{- with .Values.secret }}
  SPRING_DATASOURCE_HOST: {{ index . "dbHost" | quote}}
  SPRING_DATASOURCE_PORT: {{ index . "dbPort" | quote }}
  SPRING_DATASOURCE_NAME: {{ index . "dbName" | quote }}
  SPRING_DATASOURCE_USERNAME: {{ index . "dbUsername" | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ index . "dbPassword" | quote }}
  REDIS_HOST: {{ .redisHost | default (printf "%s-redis-master" $.Release.Name) | quote }}
  REDIS_PORT: {{ .redisPort | default "6379" | quote }}
  REDIS_TIMEOUT: {{ .redisTimeout | default "5000" | quote }} 
  REDIS_PASSWORD: {{ $.Values.redis.auth.password | quote }}
  CLIENT_ID_GOOGLE: {{ index . "idGoogle" | quote }}
  CLIENT_SECRET_GOOGLE: {{ index . "secretGoogle" | quote }}
  SECRET_BASE64: {{ index . "secretBase64" | quote }}
  AT_TIME: {{ index . "atTime" | quote }}
  RT_TIME: {{ index . "rtTime" | quote}}
  {{- end }}